# - Find CPPREST (includes and library)
# This module defines
#  CPPREST_INCLUDE_DIR
#  CPPREST_LIBRARIES
#  CPPREST_FOUND
# also defined, but not for general use are
#  CPPREST_LIBRARY, where to find the library.

if (NOT "$ENV{CPPREST_ROOT}" STREQUAL "")
  SET(CPPREST_CUSTOM_PATH $ENV{CPPREST_ROOT})
endif()

FIND_PATH(CPPREST_INCLUDE_DIR cpprest/http_listener.h
/usr/include/
/usr/local/include/
/include
${CPPREST_CUSTOM_PATH}/include
)

SET(CPPREST_NAMES ${CPPREST_NAMES} cpprest)
FIND_LIBRARY(CPPREST_LIBRARY
  NAMES ${CPPREST_NAMES}
  PATHS /usr/lib /usr/local/lib /lib /usr/lib/cpprest /usr/local/lib/cpprest /lib/cpprest /usr/lib/cpprestsdk /usr/local/lib/cpprestsdk /lib/cpprestsdk ${CPPREST_CUSTOM_PATH}/lib
  )

IF (CPPREST_LIBRARY AND CPPREST_INCLUDE_DIR)
    SET(CPPREST_LIBRARIES ${CPPREST_LIBRARY})
    SET(CPPREST_FOUND "YES")
ELSE (CPPREST_LIBRARY AND CPPREST_INCLUDE_DIR)
  SET(CPPREST_FOUND "NO")
ENDIF (CPPREST_LIBRARY AND CPPREST_INCLUDE_DIR)


IF (CPPREST_FOUND)
   IF (NOT CPPREST_FIND_QUIETLY)
      MESSAGE(STATUS "Found a CPPREST library: ${CPPREST_LIBRARIES}")
   ENDIF (NOT CPPREST_FIND_QUIETLY)
ELSE (CPPREST_FOUND)
   IF (CPPREST_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find a CPPREST library")
   ENDIF (CPPREST_FIND_REQUIRED)
ENDIF (CPPREST_FOUND)

# Deprecated declarations.
SET (NATIVE_CPPREST_INCLUDE_PATH ${CPPREST_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_CPPREST_LIB_PATH ${CPPREST_LIBRARY} PATH)

MARK_AS_ADVANCED(
  CPPREST_LIBRARY
  CPPREST_INCLUDE_DIR
  )
